name: main

on:
  push:
    branches: [ main ]
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        xcrun --show-sdk-path

    - name: Swift Package Resolve
      run: swift package resolve

    - name: Run coherent-swift report on itself
      run: swift run coherent-swift report

    - name: Sync with badge branch
      run: |
        git add .
        git commit -m "automatic: sync report and badge files"
        git push origin main:badge -f
